const express=require('express')
const router = require('./routers/user.route')
var bodyParser = require('body-parser')
const app=express()
const cors=require('cors')
require('dotenv').config()
require('./db/server')

app.use(cors())
app.use(bodyParser.json())
app.use(express.json())
app.use('/api',router)
app.listen(process.env.PORT,()=>console.log(`Server is running on port`,process.env.PORT))